"""eidt

Revision ID: dd2d34364029
Revises: 2e2a0df827a2
Create Date: 2024-05-14 07:26:07.192116

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dd2d34364029'
down_revision = '2e2a0df827a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_requirement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=255), nullable=True))
        batch_op.alter_column('gender',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=8),
               existing_nullable=True)
        batch_op.alter_column('saudi_arabia_region',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_requirement', schema=None) as batch_op:
        batch_op.alter_column('saudi_arabia_region',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.String(length=8),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
